### ISSUE TITLE
Why using suburb?

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Guadalajara#5]
@gamalielpalomo 

What is the point of having a species suburb if it is only use for display ?

**Comment by gamalielpalomo** [comment]
Hi, the idea of having suburbs comes from the models and theories (environmental criminology) that i studied before. Such theories say that all agents (offender or victim) have a routine of activities which starts and ends in a home. In this version i only identified the suburbs and residential areas in order to build the routines for each agent, but it is still a task to do.

**Comment by agrignard** [comment]
I just made a change so that we can simply give a string for the city, in order to make it work for the 3 cities can you add the neighbours.shp for miramar and tijuana?

For now I commented on the creation of the neighbor to make it working for the 3 cities
